config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 root to:'homes#top'
 get'books/new'
 get'top'=>'homes#top'
 post'books'=>'books#create'
 get'books'=>'books#index',as:'index_book'
 get'books/:id'=>'books#show',as:'book'
 get'books/:id/edit'=>'books#edit',as:'edit_book'
 patch'books/:id'=>'books#update',as:'update_book'
 delete'books/:id'=>'books#destroy',as:'destroy_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
 
  validates :title, presence: true
  validates :body, presence: true
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def index
    @books=Book.all
    @book=Book.new
  end

  def show
    @book=Book.find(params[:id])
  end



  def create
    @book=Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id),notice:'Book was successfully created.'
    else
      flash.now[:alert]='message error'
      @books=Book.all
      render :index
    end
  end

  def edit
    @book=Book.find(params[:id])
  end

  def update
    @book=Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id),notice:'Book was successfully updated.'
    else
      flash.now[:alert]='update error'
      render :edit
    end
  end

  def destroy
    book=Book.find(params[:id])
    book.destroy
    redirect_to index_book_path,notice:'Book was successfully destroyed'
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%= form_with model:@book,  local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body%>
  <%= f.submit'Update Book'%>

<% end %>

<%= link_to "show", book_path(@book.id)  %>
<%= link_to "back", index_book_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>
<div class="container">
  <div class="row">
    </div>
    <div class="col-lg-9">
    <table class="table table-striped">
      <thead>
        <tr>
         <th>Title</th>
         <th>Body</th>
         <th colspan="3"></th>
        </tr>
      </thead>

    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.body %></td>
          <td><%= link_to 'Show', book_path(book.id) %></td>
          <td><%= link_to 'Edit', edit_book_path(book.id) %></td>
          <td><%= link_to 'Destroy', destroy_book_path(book.id),method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div> 
 </div>
</div>

<h1>New Book</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%=form_with model:@book, local:true do |f|%>
  <h4>Title</h4>
  <%=f.text_field :title%>
  <h4>Body</h4>
  <%=f.text_area :body %>
  <%=f.submit'Create Book'%>
<% end %>

<br>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>


<h2>Title</h2>
<p><%=@book.title%></p>
<h2>Body</h2>
<p><%=@book.body%></p>
<%= link_to "edit", edit_book_path(@book.id) %>
<%= link_to "back", index_book_path %>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <!--<link rel="stylesheet" href="box.scss" />-->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <title>BOX</title>
  </head>
  <body>
    <h1>ようこそ<strong>Bookers</strong>へ！</h1>
    <p><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や<br>
       印象を共有し交換することができます</p>

    <!--<a href=/books>start</a>-->
     <span>
      <%=link_to 'start', "/books" %>
    </span>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--.notifications-->
    <!--- flash.each do |key, value|-->
    <!--  = content_tag(:div, value, class: key)-->
    <%= yield %>
  </body>
</html>